### ISSUE TITLE
Cannot read property 'organization' of null

### ISSUE THREAD

**Issue by ehabdevel** [the-road-to-graphql/react-graphql-github-vanilla#1]
Uncaught TypeError: Cannot read property 'organization' of null
    at App.<anonymous> (App.js:107)

_______________________

index.js:2178 The above error occurred in the <App> component:
    in App (at index.js:7)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.

_____________________________

Uncaught (in promise) TypeError: Cannot read property 'organization' of null

**Comment by rwieruch** [comment]
Thanks for reporting! Do you have the latest version and did you add your personal access token to the project? Otherwise, please check the network tab in the developer tools. Maybe the GraphQL endpoint shows you an error. Would be great to fix this issue :) 

CC @ehabdevel @chinanf-boy

**Comment by ehabdevel** [comment]
In the (Personal access tokens) in (Select scopes) section must choose ( admin:org, repo, user ) and it works fine.

**Comment by rwieruch** [comment]
Oh okay. Thanks for reporting, I will clarify it in the docs 👍

**Comment by EugeneGohh** [comment]
> Oh okay. Thanks for reporting, I will clarify it in the docs 👍

I have the same problem too. How can I fix it? I tried what you said but still can't.
