### ISSUE TITLE
App.js won't read the .env file

### ISSUE THREAD

**Issue by wetherallCode** [the-road-to-graphql/react-graphql-github-vanilla#10]
The App.js file won't read the access token from the .env file as written in the book. I needed to use dotenv to get it to work. Am I missing something, did something change recently?

**Comment by rwieruch** [comment]
It should work with the .env file. Make sure that you don't have empty .env.development or .env.production files. Also make sure to use the REACT_APP suffix for the environment variables. 

More information over here: https://facebook.github.io/create-react-app/docs/adding-custom-environment-variables

Let me know whether this helps!

**Comment by wetherallCode** [comment]
It seems to be working without using dotenv. I'm not sure why. All I did was delete the dotenv package and it worked, but I didn't do anything else. For some reason it wasn't working last night, and today it is.

**Comment by wetherallCode** [comment]
The create-react-app docs says: Environment variables are embedded into the build, meaning anyone can view them by inspecting your app's files. How would I hide the keys from the build?

**Comment by rwieruch** [comment]
You cannot hide any source code in frontend applications. Everything is available in the browser. If you have sensible information, you need to use it in your backend.

**Comment by wetherallCode** [comment]
ok
